backend/music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    path("", views.index, name="index"),
    path("registration/", views.registration, name="registration"),
]

backend/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from music import views

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'ratings', views.RatingView, 'rating')
router.register(r'registration', views.RegisterView, 'register')

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('music.urls')),
    path('api/', include(router.urls))
]

backend/music/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=255, primary_key=True, unique=True,null=False)
    password = models.CharField(max_length=255)

    def __str__(self):
        return self.username

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_auth_token(sender, instance=None, created=False, **kwargs):
        if created:
            Token.objects.create(user=instance)

#class Biography(models.Model):
    #artist = models.CharField(max_length=255, primary_key=True)
    #birthplace = models.CharField(max_length=255)
    #birthday = models.DateField()

    #def __str__(self):
        r#eturn self.artist

    #def print_facts(self):
        #birthplace = str(self.artist) + "'s " + "Birthplace: " + str(self.birthplace)
        #birthday = str(self.artist) + "'s " + "Birthday: " + str(self.birthday)
        #return [birthplace, birthday]

#class Artist(models.Model):
    #song = models.CharField(max_length=255, primary_key=True)
    #artist = models.ForeignKey(Biography, on_delete=models.CASCADE, related_name='+')
    #genre = models.CharField(max_length=255)
    #album = models.CharField(max_length=255)

    #def __str__(self):
        #return str(self.song)

class Rating(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    song = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return str(self.song) + " --> " + str(self.rating) 

backend/music/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .serializers import RatingSerializer, UserSerializer
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import User,Rating

# Create your views here.

# Our Rating view.
class RatingView(viewsets.ModelViewSet):
  # Create a new RatingSerializer instance.
  serializer_class = RatingSerializer
  # Rating.objects.all() retrieves all the Rating objects in the database.
  queryset = Rating.objects.all()

class RegisterView(viewsets.ModelViewSet):
  serializer_class = UserSerializer
  queryset = User.objects.all()

backend/music/templates/music/base.html
<form action="" method="post">
    {{form}}
    <button type="submit", name="retrieve">
</form>

backend/music/templates/music/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% load static %}
        <link rel="stylesheet" href='{% static 'css/style.css'%}'/>
        <title>Rating Retrieval</title>
    </head>
    <body>
        <div class="formContent">
            <div class="form_contain">
                <div class="header">
                    <br>
                    <h1>Retrieve your Music Ratings!</h1>
                    <br>
                </div>
                <div class="form">
                    <form action="" method="GET">
                        Username: <input type="text" name="Username" value="Enter your username" id="fill-in"/><br><br>
                        <input type="Submit" name="Submit_Username" value="Submit" id="submit"/>
                    </form>
                </div>
                <br>
                <hr>
                <br>
                <div class="header2">
                    <h3>Enter an artist's name to see fun facts!</h3>
                </div>
                <div class="form">
                    <p>Try Bill Evans!<p>
                    <br>
                    <form action="" method="GET">
                        Artist: <input type="text" name="Artist" value="Enter the artist's name" id="fill-in"/><br><br>
                        <input type="Submit" name="Submit_Artist" value="Submit" id="submit2"/>
                    </form>
                </div>
                <div class="django">
                {% if submit_username_button == "Submit" or submit_artist_button == "Submit" %}
                    <br> {{ message }} </br>
                {% endif %}
                {% for item in query %}
                    <br>{{ item }}
                {% endfor %}
                </div>
                <br>
            </div>
            <hr>
            <div class="registration">
                <br>
                <h2>New User?</h2>
                <br>
                <a href="{% url 'music:registration' %}">Click Here to Register!</a>
                <br>
                <br>
                <br>
            </div>
        </div>
        
    </body>
</html>
</DOCTYPE>

backend/music/templates/music/registration.html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% load static %}
        <link rel="stylesheet" href='{% static 'css/style1.css'%}'/>
        <title>Registration</title>
    </head>
    <body>
        <div class="formContent">
            <h2>Registration</h2>
            <form class="form" action="" method="post">
                {% csrf_token %}
                <span>Username: <input type="text" name="username" required id="username"/></span>
                <br>
                <br>
                <span>Password: <input type="password" name="password" required id="password"/></span>
                <br>
                <br>
                <span><input type="submit" name="register" value="Register" id="register_click"></span>
            </form>
            <br>
            <div id="register">
            {% if register_button == "Register" %}
            <h4> {{ error_message }} </h4>
            {% endif %}
            </div>
            <div class="main">
                <a href="{% url 'music:index' %}">Return to Rating Page</a>
            </div>
        </div>

        
    </body>
</html>
</DOCTYPE>